"""Add configuration table

Revision ID: 33ae8db5d28c
Revises: 7b2335731c2d
Create Date: 2025-05-23 23:39:55.371647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ae8db5d28c'
down_revision: Union[str, None] = '7b2335731c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            'data_type', sa.String(length=64),
            server_default=sa.text("'data_type_string'"),
            nullable=False
        ),
        sa.Column('data_key', sa.String(length=128), nullable=False),
        sa.Column('display_name', sa.String(length=256), nullable=True),
        sa.Column('data_schema', sa.Text(length=256), nullable=True),
        sa.Column('default_value', sa.Text(length=256), nullable=True),
        sa.Column('filter', sa.String(length=128), nullable=True),
        sa.Column(
            'allow_multiple', sa.Boolean(),
            server_default=sa.text('0'),
            nullable=False,
            comment='Mark true if multiple values are allowed'
        ),
        sa.Column(
            'is_secure', sa.Boolean(),
            server_default=sa.text('0'),
            nullable=False,
            comment='This field is not user editable'
        ),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('UTC_TIMESTAMP()'),
            nullable=False
        ),
        sa.Column(
            'created_by', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_by', sa.BigInteger(), nullable=True),
        sa.Column(
            'is_active', sa.Boolean(),
            server_default=sa.text('1'),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True
    )
    op.create_index(op.f('ix_configurations_data_key'), 'configurations', ['data_key'], unique=False)
    op.create_index(op.f('ix_configurations_data_type'), 'configurations', ['data_type'], unique=False)
    op.create_index(op.f('ix_configurations_id'), 'configurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configurations_id'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_data_type'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_data_key'), table_name='configurations')
    op.drop_table('configurations', if_exists=True)
    # ### end Alembic commands ###
