"""Add organization configuration table

Revision ID: 5b3efea308c9
Revises: 8547ccfb65df
Create Date: 2025-05-23 11:39:08.789248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3efea308c9'
down_revision: Union[str, None] = '8547ccfb65df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_configurations',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.BigInteger(), nullable=False),
        sa.Column('configuration_id', sa.BigInteger(), nullable=False),
        sa.Column('data_value', sa.String(length=8000), nullable=False),
        sa.Column(
            'is_default', sa.Boolean(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('UTC_TIMESTAMP()'),
            nullable=False
        ),
        sa.Column(
            'created_by', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_by', sa.BigInteger(), nullable=True),
        sa.Column(
            'is_active', sa.Boolean(),
            server_default=sa.text('1'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True
    )
    op.create_index(
        op.f('ix_organization_configurations_data_value'),
        'organization_configurations', ['data_value'], unique=False)
    op.create_index(
        op.f('ix_organization_configurations_id'),
        'organization_configurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_organization_configurations_id'),
        table_name='organization_configurations', )
    op.drop_index(
        op.f('ix_organization_configurations_data_value'),
        table_name='organization_configurations', )
    
    op.drop_table('organization_configurations', if_exists=True)
    # ### end Alembic commands ###
