"""Add lookup table

Revision ID: 7b2335731c2d
Revises: 88bb72b194a0
Create Date: 2025-05-23 11:38:50.615150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2335731c2d'
down_revision: Union[str, None] = '88bb72b194a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookups',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            'organization_id', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('lookup_type', sa.String(length=128), nullable=False),
        sa.Column('lookup_key', sa.String(length=128), nullable=False),
        sa.Column('lookup_value', sa.String(length=128), nullable=False),
        sa.Column('description', sa.String(length=8000), nullable=True),
        sa.Column(
            'is_default', sa.Boolean(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column(
            'is_secure', sa.Boolean(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column(
            'order_by', sa.Integer(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('UTC_TIMESTAMP()'),
            nullable=False
        ),
        sa.Column(
            'created_by', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_by', sa.BigInteger(), nullable=True),
        sa.Column(
            'is_active', sa.Boolean(),
            server_default=sa.text('1'),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True
    )
    op.create_index(
        op.f('ix_public_lookups_id'), 'lookups', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_public_lookups_lookup_key'), 'lookups', ['lookup_key'], unique=False
    )
    op.create_index(
        op.f('ix_public_lookups_lookup_type'), 'lookups', ['lookup_type'], unique=False
    )
    op.create_index(
        op.f('ix_public_lookups_lookup_value'), 'lookups', ['lookup_value'], unique=False
    )
    op.create_index(op.f('ix_public_lookups_organization_id'), 'lookups', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_lookups_organization_id'), table_name='lookups')
    op.drop_index(op.f('ix_public_lookups_lookup_value'), table_name='lookups')
    op.drop_index(op.f('ix_public_lookups_lookup_type'), table_name='lookups')
    op.drop_index(op.f('ix_public_lookups_lookup_key'), table_name='lookups')
    op.drop_index(op.f('ix_public_lookups_id'), table_name='lookups')
    op.drop_table('lookups', if_exists=True)
    # ### end Alembic commands ###
