"""Add organization table

Revision ID: 8547ccfb65df
Revises: 00034a3680df
Create Date: 2025-05-23 11:38:56.143665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8547ccfb65df'
down_revision: Union[str, None] = '00034a3680df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            'hash', sa.String(length=36),
            server_default=sa.text('UUID()'),
            unique=True, index=True,
            nullable=False
        ),
        sa.Column('type_id', sa.BigInteger(), nullable=False),
        sa.Column('display_name', sa.String(length=128), nullable=False),
        sa.Column('legal_name', sa.String(length=128), nullable=True),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.Column('logo', sa.String(length=256), nullable=True),
        sa.Column('subdomain', sa.String(length=128), nullable=True),
        sa.Column('custom_domain', sa.String(length=128), nullable=True),
        sa.Column('address', sa.String(length=256), nullable=True),
        sa.Column('locality', sa.String(length=256), nullable=True),
        sa.Column('city', sa.String(length=128), nullable=True),
        sa.Column('state_id', sa.Integer(), nullable=True),
        sa.Column('country_id', sa.Integer(), nullable=True),
        sa.Column('zipcode', sa.String(length=32), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('phone', sa.String(length=32), nullable=True),
        sa.Column('email', sa.String(length=128), nullable=True),
        sa.Column('search_tags', sa.String(length=256), nullable=True),
        sa.Column('website', sa.String(length=256), nullable=True),
        sa.Column('payment_provider', sa.String(length=128), nullable=True),
        sa.Column('payment_provider_customer_id', sa.String(length=128), nullable=True),
        sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('UTC_TIMESTAMP()'),
            nullable=False
        ),
        sa.Column(
            'created_by', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_by', sa.BigInteger(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.BigInteger(), nullable=True),
        sa.Column(
            'is_active', sa.Boolean(),
            server_default=sa.text('1'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['type_id'], ['lookups.id'], ),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True
    )
    op.create_index(
        op.f('ix_public_organizations_custom_domain'),
        'organizations', ['custom_domain'], unique=False)
    op.create_index(
        op.f('ix_public_organizations_display_name'),
        'organizations', ['display_name'], unique=False)
    op.create_index(
        op.f('ix_public_organizations_hash'),
        'organizations', ['hash'], unique=True)
    op.create_index(
        op.f('ix_public_organizations_id'),
        'organizations', ['id'], unique=False)
    op.create_index(
        op.f('ix_public_organizations_subdomain'),
        'organizations', ['subdomain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_public_organizations_subdomain'),
        table_name='organizations')
    op.drop_index(
        op.f('ix_public_organizations_id'),
        table_name='organizations')
    op.drop_index(
        op.f('ix_public_organizations_hash'),
        table_name='organizations')
    op.drop_index(
        op.f('ix_public_organizations_display_name'),
        table_name='organizations')
    op.drop_index(
        op.f('ix_public_organizations_custom_domain'),
        table_name='organizations')
    
    op.drop_table('organizations', if_exists=True)
    # ### end Alembic commands ###
