"""Add initial migrations

Revision ID: 88bb72b194a0
Revises: 
Create Date: 2025-05-23 00:32:50.462895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bb72b194a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('lookup_type', sa.String(length=128), nullable=False),
    sa.Column('lookup_key', sa.String(length=128), nullable=False),
    sa.Column('lookup_value', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=8000), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_secure', sa.Boolean(), nullable=False),
    sa.Column('order_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_lookups_id'), 'lookups', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_lookups_lookup_key'), 'lookups', ['lookup_key'], unique=False, schema='public')
    op.create_index(op.f('ix_public_lookups_lookup_type'), 'lookups', ['lookup_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_lookups_lookup_value'), 'lookups', ['lookup_value'], unique=False, schema='public')
    op.create_index(op.f('ix_public_lookups_organization_id'), 'lookups', ['organization_id'], unique=False, schema='public')
    
    op.create_table('organizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('type_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('legal_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('logo', sa.String(length=256), nullable=True),
    sa.Column('subdomain', sa.String(length=128), nullable=True),
    sa.Column('custom_domain', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('locality', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('zipcode', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('search_tags', sa.String(length=256), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('payment_provider', sa.String(length=128), nullable=True),
    sa.Column('payment_provider_customer_id', sa.String(length=128), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['public.lookups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_organizations_custom_domain'), 'organizations', ['custom_domain'], unique=False, schema='public')
    op.create_index(op.f('ix_public_organizations_display_name'), 'organizations', ['display_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_organizations_hash'), 'organizations', ['hash'], unique=True, schema='public')
    op.create_index(op.f('ix_public_organizations_id'), 'organizations', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_organizations_subdomain'), 'organizations', ['subdomain'], unique=False, schema='public')
    
    op.create_table('organization_configurations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('data_type', sa.String(length=128), nullable=False),
    sa.Column('data_key', sa.String(length=128), nullable=False),
    sa.Column('data_value', sa.String(length=8000), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_secure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_organization_configurations_data_key'), 'organization_configurations', ['data_key'], unique=False, schema='public')
    op.create_index(op.f('ix_public_organization_configurations_data_type'), 'organization_configurations', ['data_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_organization_configurations_data_value'), 'organization_configurations', ['data_value'], unique=False, schema='public')
    op.create_index(op.f('ix_public_organization_configurations_id'), 'organization_configurations', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_organization_configurations_id'), table_name='organization_configurations', schema='public')
    op.drop_index(op.f('ix_public_organization_configurations_data_value'), table_name='organization_configurations', schema='public')
    op.drop_index(op.f('ix_public_organization_configurations_data_type'), table_name='organization_configurations', schema='public')
    op.drop_index(op.f('ix_public_organization_configurations_data_key'), table_name='organization_configurations', schema='public')
    op.drop_table('organization_configurations', schema='public')
    
    op.drop_index(op.f('ix_public_organizations_subdomain'), table_name='organizations', schema='public')
    op.drop_index(op.f('ix_public_organizations_id'), table_name='organizations', schema='public')
    op.drop_index(op.f('ix_public_organizations_hash'), table_name='organizations', schema='public')
    op.drop_index(op.f('ix_public_organizations_display_name'), table_name='organizations', schema='public')
    op.drop_index(op.f('ix_public_organizations_custom_domain'), table_name='organizations', schema='public')
    op.drop_table('organizations', schema='public')
    
    op.drop_index(op.f('ix_public_lookups_organization_id'), table_name='lookups', schema='public')
    op.drop_index(op.f('ix_public_lookups_lookup_value'), table_name='lookups', schema='public')
    op.drop_index(op.f('ix_public_lookups_lookup_type'), table_name='lookups', schema='public')
    op.drop_index(op.f('ix_public_lookups_lookup_key'), table_name='lookups', schema='public')
    op.drop_index(op.f('ix_public_lookups_id'), table_name='lookups', schema='public')
    op.drop_table('lookups', schema='public')
    # ### end Alembic commands ###
